{
    "MonsoonIntensity": [75],
    # "TopographyDrainage": [60],
    "RiverManagement": [80],
    "Deforestation": [40],
    "Urbanization": [70],
    "ClimateChange": [65],
    "DamsQuality": [50],
    "Siltation": [55],
    "AgriculturalPractices": [60],
    "Encroachments": [50],
    "IneffectiveDisasterPreparedness": [45],
    "DrainageSystems": [70],
    "CoastalVulnerability": [65],
    "Landslides": [30],
    "Watersheds": [50],
    "DeterioratingInfrastructure": [55],
    "PopulationScore": [80],
    "WetlandLoss": [60],
    "InadequatePlanning": [50],
    "PoliticalFactors": [55],
}
